from io import BytesIO
from django.http import FileResponse
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime

def generate_withdrawal_receipt(transaction):
    """ Generate a PDF receipt dynamically for a completed withdrawal transaction. """

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    
    # Title
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(200, 800, "Withdrawal Receipt")
    
    # Employee Details
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, 750, f"Employee Name: {transaction.request.employee.full_name()}")
    pdf.drawString(50, 730, f"NITDA ID: {transaction.request.employee.nitda_id}")

    # Transaction Details
    pdf.drawString(50, 700, f"Withdrawal Amount: ₦{transaction.amount}")
    pdf.drawString(50, 680, f"Charge Deducted: ₦{transaction.charge}")
    pdf.drawString(50, 660, f"Final Amount Received: ₦{transaction.final_amount}")
    pdf.drawString(50, 640, f"Remaining Savings Balance: ₦{transaction.savings_remain}")
    
    pdf.drawString(50, 610, f"Reference Number: {transaction.reference_number}")
    pdf.drawString(50, 590, f"Transaction Date: {transaction.transaction_date.strftime('%Y-%m-%d')}")

    # Bank Account Details
    account_details = transaction.request.employee.account_details
    pdf.drawString(50, 560, f"Paid To This Bank Details")
    pdf.drawString(50, 540, f"Bank Name: {account_details.bank_name}")
    pdf.drawString(50, 520, f"Account Number: {account_details.account_number}")
    pdf.drawString(50, 500, f"Account Holder: {account_details.account_holder_name}")

    # Footer
    pdf.drawString(50, 470, "Thank you for using our service.")
    pdf.drawString(50, 450, "Receipt generated by BCS Tracking System.")

    pdf.showPage()
    pdf.save()
    
    buffer.seek(0)
    return buffer
