# Generated by Django 5.1.6 on 2025-02-09 00:28

import django.db.models.deletion
import loan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('Qard Hasan', 'Qard Hasan (Cash Loan)'), ('Murabaha', 'Murabaha (Asset-Based Financing)')], max_length=50)),
                ('purpose', models.TextField()),
                ('repayment_period', models.IntegerField()),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Disbursed', 'Disbursed'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('guarantors_approval', models.BooleanField(default=False)),
                ('tracking_id', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('action_note', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applicant', to=settings.AUTH_USER_MODEL)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='GracePeriodExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_request_date', models.DateTimeField(auto_now_add=True)),
                ('extension_duration', models.IntegerField()),
                ('reason_for_extension', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('action_note', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='ActionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Disbursed', 'Disbursed'), ('Paid', 'Paid'), ('Accepted', 'Accepted')], max_length=20)),
                ('note', models.TextField()),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_by', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_notes', to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_signed_date', models.DateTimeField(auto_now_add=True)),
                ('agreement_terms', models.TextField()),
                ('status', models.CharField(choices=[('Signed', 'Signed'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Reviewer', 'Reviewer'), ('Approver', 'Approver')], max_length=50)),
                ('committee_member_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_committee_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.CharField(choices=[('Okay', 'Okay'), ('Not Okay', 'Not Okay'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], max_length=50)),
                ('action_reason', models.TextField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_actions', to='loan.loan')),
                ('committee_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='loan.loancommittee')),
            ],
        ),
        migrations.CreateModel(
            name='MurabahaLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[loan.models.validate_positive])),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[loan.models.validate_positive])),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=12, validators=[loan.models.validate_positive])),
                ('total_loan_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('asset_image', models.ImageField(blank=True, null=True, upload_to='murabaha/assets_images/')),
                ('created_at', models.DateField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='QardHasanLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_loan_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[loan.models.validate_positive])),
                ('administrative_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[loan.models.validate_positive])),
                ('created_at', models.DateField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_method', models.CharField(choices=[('salary', 'Salary Deduction'), ('direct', 'Direct Deposit'), ('both', 'Both Method')], max_length=6)),
                ('repayment_start_date', models.DateField()),
                ('repayment_end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], max_length=20)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_date', models.DateTimeField()),
                ('repayment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_method', models.CharField(choices=[('Salary Deduction', 'Salary Deduction'), ('Direct Deposit', 'Direct Deposit'), ('both', 'Both Method')], max_length=20)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
                ('repayment_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loan.repaymentsetting')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Repayment', 'Repayment'), ('Loan Disbursement', 'Loan Disbursement'), ('Penalty', 'Penalty')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_description', models.TextField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
    ]
