# Generated by Django 5.1.6 on 2025-02-09 11:08

import django.utils.timezone
import loan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantor',
            name='applicant',
        ),
        migrations.AddField(
            model_name='loan',
            name='details_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantors_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_setting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repaymentsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='murabahaloan',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[loan.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='repaymentsetting',
            name='repayment_end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='repaymentsetting',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Overdue', 'Overdue'), ('Not Started', 'Not Started')], default='Not Started', max_length=20),
        ),
    ]
