# Generated by Django 5.1.6 on 2025-02-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_remove_guarantor_applicant_loan_details_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Disbursed', 'Disbursed'), ('Paid', 'Paid'), ('Not Finished', 'Apllication Not Finish')], default='Not Finish', max_length=20),
        ),
        migrations.AlterField(
            model_name='murabahaloan',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='murabaha', to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='qardhasanloan',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qard_hasan', to='loan.loan'),
        ),
    ]
