# Generated by Django 5.1.6 on 2025-02-09 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_status_alter_murabahaloan_loan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Disbursed', 'Disbursed'), ('Paid', 'Paid'), ('Not Finished', 'Apllication Not Finish')], default='Not Finished', max_length=20),
        ),
        migrations.AlterField(
            model_name='repaymentsetting',
            name='repayment_end_date',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Date must be in YYYY-MM format.', regex='^\\d{4}-(0[1-9]|1[0-2])$')]),
        ),
        migrations.AlterField(
            model_name='repaymentsetting',
            name='repayment_start_date',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Date must be in YYYY-MM format.', regex='^\\d{4}-(0[1-9]|1[0-2])$')]),
        ),
    ]
