# Generated by Django 5.1.6 on 2025-02-09 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentsetting',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_settings', to='loan.loan'),
        ),
    ]
