# Generated by Django 5.1.6 on 2025-02-09 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_repaymentsetting_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='guarantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loan.loan'),
        ),
    ]
