# Generated by Django 5.1.6 on 2025-02-09 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_guarantor_guarantor_alter_guarantor_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancommittee',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_committee_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
