# Generated by Django 5.1.6 on 2025-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_other_name_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
