# Generated by Django 5.1.6 on 2025-03-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
