# Generated by Django 5.1.6 on 2025-02-24 19:46

import credit.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(choices=[('Qard Hasan', 'Qard Hasan (Cash Credit)'), ('Murabaha', 'Murabaha (Asset-Based Financing)'), ('Musharaka', 'Musharaka (Partnership-Based Financing)'), ('Ijarah', 'Ijarah (Leasing-Based Financing)')], max_length=50)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('repayment_period', models.IntegerField(help_text='Repayment duration in months.', validators=[django.core.validators.MinValueValidator(1)])),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Disbursed', 'Disbursed'), ('Repaid', 'Repaid')], default='Pending', max_length=20)),
                ('guarantors_approval', models.BooleanField(default=False)),
                ('guarantors_added', models.BooleanField(default=False)),
                ('tracking_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('administrative_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed administrative charge applied.', max_digits=10)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Reviewer', 'Reviewer'), ('Approver', 'Approver')], max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_committee_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.CharField(choices=[('Okay', 'Okay'), ('Not Okay', 'Not Okay'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], max_length=50)),
                ('action_reason', models.TextField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_actions', to='credit.credit')),
                ('committee_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='credit.creditcommittee')),
            ],
        ),
        migrations.CreateModel(
            name='CreditSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_repayment_months', models.IntegerField(default=10, help_text='Maximum number of months allowed for credit repayment.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('savings_credit_ratio', models.DecimalField(decimal_places=2, default=60.0, help_text='Percentage of savings that can be used for credit (0-100%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('open_days', models.JSONField(default=['Tuesday', 'Wednesday'], help_text="Days of the week when credit applications are open. Format: ['Monday', 'Wednesday', 'Friday']")),
                ('admin_charge_value', models.DecimalField(decimal_places=2, default=3000.0, help_text='The fixed amount of administrative charge.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_credit_amount', models.DecimalField(decimal_places=2, default=10000.0, help_text='Minimum amount an applicant can apply for.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('enable_qard_hasan', models.BooleanField(default=True, help_text='Enable or disable Qard Hasan credit type.')),
                ('enable_murabaha', models.BooleanField(default=True, help_text='Enable or disable Murabaha credit type.')),
                ('enable_musharaka', models.BooleanField(default=True, help_text='Enable or disable Musharaka credit type.')),
                ('enable_ijarah', models.BooleanField(default=True, help_text='Enable or disable Ijarah credit type.')),
                ('min_savings_required', models.DecimalField(decimal_places=2, default=5000.0, help_text='Minimum savings balance required before being eligible for credit.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last admin who updated the settings.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Setting',
                'verbose_name_plural': 'Credit Settings',
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('action_note', models.TextField(blank=True, null=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='credit.credit')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ijarah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('lease_period', models.IntegerField()),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[credit.models.validate_positive])),
                ('created_at', models.DateField(auto_now=True)),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ijarah', to='credit.credit')),
            ],
        ),
        migrations.CreateModel(
            name='Murabaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[credit.models.validate_positive])),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[credit.models.validate_positive])),
                ('total_credit_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('vendor_invoice', models.ImageField(blank=True, null=True, upload_to='murabaha/vendor_invoice/')),
                ('created_at', models.DateField(auto_now=True)),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='murabaha', to='credit.credit')),
            ],
        ),
        migrations.CreateModel(
            name='Musharaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_contribution', models.DecimalField(decimal_places=2, max_digits=12, validators=[credit.models.validate_positive])),
                ('profit_sharing_ratio', models.DecimalField(decimal_places=2, max_digits=5, validators=[credit.models.validate_positive])),
                ('created_at', models.DateField(auto_now=True)),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='musharaka', to='credit.credit')),
            ],
        ),
        migrations.CreateModel(
            name='QardHasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credit_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[credit.models.validate_positive])),
                ('administrative_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[credit.models.validate_positive])),
                ('created_at', models.DateField(auto_now=True)),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qard_hasan', to='credit.credit')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_method', models.CharField(choices=[('S', 'Salary Deduction'), ('D', 'Direct Deposit')], default='S', max_length=1)),
                ('status', models.CharField(choices=[('Repaid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], max_length=20)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.credit')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('R', 'Repayment'), ('C', 'Credit Disbursement')], max_length=2)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_description', models.TextField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.credit')),
            ],
        ),
    ]
