# Generated by Django 5.1.6 on 2025-02-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murabaha',
            name='total_credit_amount',
        ),
        migrations.AlterField(
            model_name='creditsettings',
            name='open_days',
            field=models.JSONField(default=['Tuesday', 'Wednesday'], help_text='Days of the week when credit applications are open.'),
        ),
        migrations.DeleteModel(
            name='QardHasan',
        ),
    ]
