# Generated by Django 5.1.6 on 2025-02-26 12:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_remove_murabaha_total_credit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='amount_requested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
