# Generated by Django 5.1.6 on 2025-02-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_credit_amount_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='amount_repaid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditsettings',
            name='open_days',
            field=models.JSONField(default=list, help_text='Days of the week when credit applications are open.'),
        ),
    ]
