# Generated by Django 5.1.6 on 2025-02-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_credit_amount_repaid_alter_creditsettings_open_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='guarantors_added',
            new_name='guarantor_approval',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='guarantors_approval',
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
