# Generated by Django 5.1.6 on 2025-02-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_rename_guarantors_added_credit_guarantor_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantor',
            name='action_note',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='transaction_description',
        ),
        migrations.AddField(
            model_name='credit',
            name='repayment_start_month',
            field=models.IntegerField(blank=True, help_text='Month when repayment starts.', null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transaction_receipt',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='transaction_receipts/'),
        ),
        migrations.AlterField(
            model_name='committeeaction',
            name='action_taken',
            field=models.CharField(choices=[('Okay', 'Okay'), ('Not Okay', 'Not Okay'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=50),
        ),
    ]
