# Generated by Django 5.1.6 on 2025-02-28 12:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_remove_guarantor_action_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='monthly_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly deduction amount for credit repayment.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
