# Generated by Django 5.1.6 on 2025-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_credit_monthly_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='repayment_start_month',
        ),
        migrations.AddField(
            model_name='credit',
            name='repayment_start_date',
            field=models.DateField(blank=True, help_text='Date when repayment starts (YYYY-MM).', null=True),
        ),
    ]
