# Generated by Django 5.1.6 on 2025-02-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_remove_credit_repayment_start_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='repayment_start_date',
        ),
        migrations.AddField(
            model_name='credit',
            name='repayment_start_month',
            field=models.CharField(blank=True, help_text='Date when repayment starts (YYYY-MM).', max_length=7, null=True),
        ),
    ]
