# Generated by Django 5.1.6 on 2025-02-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_remove_credit_repayment_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repayment',
            name='remaining_balance',
        ),
        migrations.AlterField(
            model_name='repayment',
            name='repayment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
