# Generated by Django 5.1.6 on 2025-03-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0010_remove_repayment_remaining_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='murabaha',
            old_name='asset_value',
            new_name='asset_price',
        ),
        migrations.AddField(
            model_name='murabaha',
            name='profit_margin_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='murabaha',
            name='profit_margin_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='murabaha',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
