# Generated by Django 5.1.6 on 2025-03-01 06:44

import credit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0011_rename_asset_value_murabaha_asset_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murabaha',
            name='vendor_invoice',
            field=models.FileField(blank=True, null=True, upload_to='murabaha/vendor_invoice/', validators=[credit.models.validate_file_extension]),
        ),
    ]
