# Generated by Django 5.1.6 on 2025-03-06 14:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionChangeRequest',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contribution_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionSetting',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionSettingHistory',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_setting_changes', to=settings.AUTH_USER_MODEL)),
                ('contribution_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='operations.contributionsetting')),
            ],
        ),
        migrations.CreateModel(
            name='TargetSavings',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('W-R', 'Withdrawal Request'), ('completed', 'Completed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wthdrawed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetSavingsTransaction',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='target_contribution_ransaction/receipts/')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('target_savings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='operations.targetsavings')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionRecord',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='paid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
