# Generated by Django 5.1.6 on 2025-02-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_contributionchangerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContributionSettingPermissions',
        ),
    ]
