# Generated by Django 5.1.6 on 2025-03-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_contributionrecord_status_targetcontribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetcontribution',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='targetcontributiontransaction',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
