# Generated by Django 5.1.6 on 2025-03-04 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_targetcontribution_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetcontributiontransaction',
            name='target',
        ),
        migrations.RemoveField(
            model_name='targetcontributiontransaction',
            name='member',
        ),
        migrations.CreateModel(
            name='TargetSavings',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('interest', models.TextField(help_text="Describe what you're saving towards.")),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wthdrawed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetSavingsTransaction',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='target_contribution_ransaction/receipts/')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('target_savings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='operations.targetsavings')),
            ],
        ),
        migrations.DeleteModel(
            name='TargetContribution',
        ),
        migrations.DeleteModel(
            name='TargetContributionTransaction',
        ),
    ]
