# Generated by Django 5.1.6 on 2025-03-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_remove_targetcontributiontransaction_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetsavings',
            name='interest',
        ),
    ]
