# Generated by Django 5.1.6 on 2025-03-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_remove_targetsavings_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsavings',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('W-R', 'Withdrawal Request'), ('completed', 'Completed')], default='active', max_length=10),
        ),
    ]
