# Generated by Django 5.1.6 on 2025-02-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='withdrawalcharge',
            unique_together={('withdrawal_type', 'charge_percentage', 'reason')},
        ),
    ]
