# Generated by Django 5.1.6 on 2025-02-08 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0003_alter_withdrawalrequest_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='death_certificate',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='retirement_letter',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='voluntary_letter',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='withdrawals/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='document_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='reason',
            field=models.CharField(blank=True, choices=[('death', 'Death'), ('voluntary', 'Voluntary'), ('retirement', 'Retirement')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
