# Generated by Django 5.1.6 on 2025-02-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0004_remove_withdrawalrequest_death_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='current_stage',
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='document_type',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
