# Generated by Django 5.1.6 on 2025-02-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0005_remove_withdrawalrequest_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='action_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='action_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
