# Generated by Django 5.1.6 on 2025-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0006_withdrawalrequest_action_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawaltransaction',
            name='savings_remain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
