# Generated by Django 5.1.6 on 2025-02-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0007_withdrawaltransaction_savings_remain'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
