# Generated by Django 5.1.6 on 2025-02-16 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0008_withdrawalrequest_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('current', 'Current'), ('deprecated', 'Deprecated')], default='current', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('action_note', models.TextField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('saving_balance_remain', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeesavings',
            name='employee',
        ),
        migrations.DeleteModel(
            name='WithdrawalCharge',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='withdrawaltransaction',
            name='request',
        ),
        migrations.DeleteModel(
            name='EmployeeSavings',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
        migrations.DeleteModel(
            name='WithdrawalTransaction',
        ),
    ]
