# Generated by Django 5.1.6 on 2025-02-16 16:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0009_charges_withdrawals_remove_employeesavings_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawals',
            name='charges_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='withdrawals',
            name='total_amount_withdrawn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='saving_balance_remain',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
