# Generated by Django 5.1.6 on 2025-02-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0010_withdrawals_charges_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawals',
            name='saving_balance_remain',
        ),
    ]
