# Generated by Django 5.1.6 on 2025-03-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0011_remove_withdrawals_saving_balance_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeaccountdetails',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
